name: flower_e_commerce_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_timer_countdown: ^1.0.7
  get_it: ^8.2.0
  injectable: ^2.5.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.0
  responsive_framework: ^1.5.1
  easy_localization: ^3.0.8
  image_picker: ^1.2.0
  shimmer_animation: ^2.2.2
  flutter_image_slideshow: ^0.1.6
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  geocoding: ^2.1.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  pinput: ^5.0.1
  bloc_test: ^10.0.0
  equatable: ^2.0.7
  step_progress: ^2.7.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.2
  location: ^8.0.1
  firebase_database: ^12.0.2
  http: ^1.2.1
  flutter_polyline_points: ^2.0.0
  flutter_dotenv: ^5.1.0
  awesome_snackbar_content: ^0.1.8
  webview_flutter: ^4.13.0
  fluttertoast: ^9.0.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  test: ^1.25.15
  json_serializable: ^6.10.0

  retrofit_generator: ^10.0.4

  injectable_generator: ^2.8.1

  mockito: ^5.5.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/json/
    - assets/mapStyles/
    - assets/animations/
    - .env
    - assets/json/aboutus.json
    - assets/json/termsconditions.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
flutter_assets:
  assets_path: assets/images/
  output_path: lib\core\utils\Constantts\
  filename: app_assets.dart
