// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKbc5K-neVHKcve9jGprTUpTtT-d_VaEk',
    appId: '1:358889392218:web:4598ad9bc7ce09ffbf7063',
    messagingSenderId: '358889392218',
    projectId: 'flowery-5f3a6',
    authDomain: 'flowery-5f3a6.firebaseapp.com',
    storageBucket: 'flowery-5f3a6.firebasestorage.app',
    measurementId: 'G-S6412SJC68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDANxPvIjBlJJQLZ3zaz2xJQhpddSKXBbM',
    appId: '1:358889392218:android:3a0cf0d5886b7417bf7063',
    messagingSenderId: '358889392218',
    projectId: 'flowery-5f3a6',
    storageBucket: 'flowery-5f3a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6LBA36Dl_qKFKtPSoCj2SMDwStnc8JoQ',
    appId: '1:358889392218:ios:fcdbdd766aaa403ebf7063',
    messagingSenderId: '358889392218',
    projectId: 'flowery-5f3a6',
    storageBucket: 'flowery-5f3a6.firebasestorage.app',
    iosBundleId: 'com.example.flowerECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6LBA36Dl_qKFKtPSoCj2SMDwStnc8JoQ',
    appId: '1:358889392218:ios:fcdbdd766aaa403ebf7063',
    messagingSenderId: '358889392218',
    projectId: 'flowery-5f3a6',
    storageBucket: 'flowery-5f3a6.firebasestorage.app',
    iosBundleId: 'com.example.flowerECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKbc5K-neVHKcve9jGprTUpTtT-d_VaEk',
    appId: '1:358889392218:web:f90ae1a82b816d57bf7063',
    messagingSenderId: '358889392218',
    projectId: 'flowery-5f3a6',
    authDomain: 'flowery-5f3a6.firebaseapp.com',
    storageBucket: 'flowery-5f3a6.firebasestorage.app',
    measurementId: 'G-37YPWQD7X6',
  );

}