// Mocks generated by Mockito 5.4.6 from annotations
// in flower_e_commerce_app/test/Feature/auth/api/dataSources/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flower_e_commerce_app/Feature/auth/api/client/api_service.dart'
    as _i8;
import 'package:flower_e_commerce_app/Feature/auth/api/models/request/forget_password_request.dart'
    as _i11;
import 'package:flower_e_commerce_app/Feature/auth/api/models/request/reset_password_request.dart'
    as _i13;
import 'package:flower_e_commerce_app/Feature/auth/api/models/request/sign_in_request_dto.dart'
    as _i10;
import 'package:flower_e_commerce_app/Feature/auth/api/models/request/sign_up_request_model.dart'
    as _i14;
import 'package:flower_e_commerce_app/Feature/auth/api/models/request/verify_reset_code_request.dart'
    as _i12;
import 'package:flower_e_commerce_app/Feature/auth/api/models/response/forget_password_response_dto.dart'
    as _i3;
import 'package:flower_e_commerce_app/Feature/auth/api/models/response/logout_response_dto.dart'
    as _i7;
import 'package:flower_e_commerce_app/Feature/auth/api/models/response/reset_password_response_dto.dart'
    as _i5;
import 'package:flower_e_commerce_app/Feature/auth/api/models/response/sign_in_response_dto.dart'
    as _i2;
import 'package:flower_e_commerce_app/Feature/auth/api/models/response/sign_up_response_dto.dart'
    as _i6;
import 'package:flower_e_commerce_app/Feature/auth/api/models/response/verify_reset_code_response_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSigninResponseDto_0 extends _i1.SmartFake
    implements _i2.SigninResponseDto {
  _FakeSigninResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetPasswordResponseDto_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyResetCodeResponseDto_2 extends _i1.SmartFake
    implements _i4.VerifyResetCodeResponseDto {
  _FakeVerifyResetCodeResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignUpResponseDto_4 extends _i1.SmartFake
    implements _i6.SignUpResponseDto {
  _FakeSignUpResponseDto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogoutResponseDto_5 extends _i1.SmartFake
    implements _i7.LogoutResponseDto {
  _FakeLogoutResponseDto_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i8.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.SigninResponseDto> signIn(
          {required _i10.SigninRequestDto? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {#request: request},
        ),
        returnValue:
            _i9.Future<_i2.SigninResponseDto>.value(_FakeSigninResponseDto_0(
          this,
          Invocation.method(
            #signIn,
            [],
            {#request: request},
          ),
        )),
      ) as _i9.Future<_i2.SigninResponseDto>);

  @override
  _i9.Future<_i3.ForgetPasswordResponseDto> forgetPassword(
          _i11.ForgetPasswordRequest? forgetPasswordRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [forgetPasswordRequest],
        ),
        returnValue: _i9.Future<_i3.ForgetPasswordResponseDto>.value(
            _FakeForgetPasswordResponseDto_1(
          this,
          Invocation.method(
            #forgetPassword,
            [forgetPasswordRequest],
          ),
        )),
      ) as _i9.Future<_i3.ForgetPasswordResponseDto>);

  @override
  _i9.Future<_i4.VerifyResetCodeResponseDto> verifyResetCode(
          _i12.VerifyResetCodeRequest? verifyResetCodeRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [verifyResetCodeRequest],
        ),
        returnValue: _i9.Future<_i4.VerifyResetCodeResponseDto>.value(
            _FakeVerifyResetCodeResponseDto_2(
          this,
          Invocation.method(
            #verifyResetCode,
            [verifyResetCodeRequest],
          ),
        )),
      ) as _i9.Future<_i4.VerifyResetCodeResponseDto>);

  @override
  _i9.Future<_i5.ResetPasswordResponseDto> resetPassword(
          _i13.ResetPasswordRequest? resetPasswordRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [resetPasswordRequest],
        ),
        returnValue: _i9.Future<_i5.ResetPasswordResponseDto>.value(
            _FakeResetPasswordResponseDto_3(
          this,
          Invocation.method(
            #resetPassword,
            [resetPasswordRequest],
          ),
        )),
      ) as _i9.Future<_i5.ResetPasswordResponseDto>);

  @override
  _i9.Future<_i6.SignUpResponseDto> signUp(
          _i14.SignUpRequestModel? signUpRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [signUpRequest],
        ),
        returnValue:
            _i9.Future<_i6.SignUpResponseDto>.value(_FakeSignUpResponseDto_4(
          this,
          Invocation.method(
            #signUp,
            [signUpRequest],
          ),
        )),
      ) as _i9.Future<_i6.SignUpResponseDto>);

  @override
  _i9.Future<_i7.LogoutResponseDto> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i9.Future<_i7.LogoutResponseDto>.value(_FakeLogoutResponseDto_5(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i9.Future<_i7.LogoutResponseDto>);
}
