name: Flutter Unit Testing Action

on:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Create .env file with secrets
        run: |
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
          echo ".env file created successfully"

      - name: Delete pubspec.lock
        run: |
          if [ -f pubspec.lock ]; then
            echo "Deleting pubspec.lock..."
            rm pubspec.lock
          else
            echo "pubspec.lock not found, skipping"
          fi
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code (json_serializable, retrofit, mockito)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test
